/*
 * File:           \\VBOXSVR\VirtualBox_VMs\SigmaStudioProjects\ADAU1452\filter96k_1452\filter96k_1452_IC 1\filter96k_1452_IC_1_PARAM.h
 *
 * Created:        Friday, June 05, 2020 5:52:25 PM
 * Description:    filter96k_1452:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2020 Analog Devices, Inc. All rights reserved.
 */
#ifndef __FILTER96K_1452_IC_1_PARAM_H__
#define __FILTER96K_1452_IC_1_PARAM_H__


/* Module SafeLoadModule - SafeLoadModule*/
#define MOD_SAFELOADMODULE_COUNT                       13
#define MOD_SAFELOADMODULE_DEVICE                      "IC1"
#define MOD_SAFELOADMODULE_DATA_SAFELOAD0_ADDR         24576
#define MOD_SAFELOADMODULE_DATA_SAFELOAD1_ADDR         24577
#define MOD_SAFELOADMODULE_DATA_SAFELOAD2_ADDR         24578
#define MOD_SAFELOADMODULE_DATA_SAFELOAD3_ADDR         24579
#define MOD_SAFELOADMODULE_DATA_SAFELOAD4_ADDR         24580
#define MOD_SAFELOADMODULE_ADDRESS_SAFELOAD_ADDR       24581
#define MOD_SAFELOADMODULE_NUM_SAFELOAD_ADDR           24582

/* Module Pulse1 - Pulse with dynamic duty cycle*/
#define MOD_PULSE1_COUNT                               4
#define MOD_PULSE1_DEVICE                              "IC1"
#define MOD_PULSE1_ALG0_ISROUNDED_ADDR                 24
#define MOD_PULSE1_ALG0_ISROUNDED_VALUE                SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_PULSE1_ALG0_ISROUNDED_TYPE                 SIGMASTUDIOTYPE_8_24
#define MOD_PULSE1_ALG0_FREQ_STEP_ADDR                 25
#define MOD_PULSE1_ALG0_FREQ_STEP_VALUE                SIGMASTUDIOTYPE_8_24_CONVERT(0.000104166666666667)
#define MOD_PULSE1_ALG0_FREQ_STEP_TYPE                 SIGMASTUDIOTYPE_8_24
#define MOD_PULSE1_ALG0_ON_ADDR                        26
#define MOD_PULSE1_ALG0_ON_VALUE                       SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_PULSE1_ALG0_ON_TYPE                        SIGMASTUDIOTYPE_8_24
#define MOD_PULSE1_ALG0_TH_ADDR                        27
#define MOD_PULSE1_ALG0_TH_VALUE                       SIGMASTUDIOTYPE_8_24_CONVERT(0.5)
#define MOD_PULSE1_ALG0_TH_TYPE                        SIGMASTUDIOTYPE_8_24

/* Module Pulse2 - Pulse with dynamic duty cycle*/
#define MOD_PULSE2_COUNT                               4
#define MOD_PULSE2_DEVICE                              "IC1"
#define MOD_PULSE2_ALG0_ISROUNDED_ADDR                 28
#define MOD_PULSE2_ALG0_ISROUNDED_VALUE                SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_PULSE2_ALG0_ISROUNDED_TYPE                 SIGMASTUDIOTYPE_8_24
#define MOD_PULSE2_ALG0_FREQ_STEP_ADDR                 29
#define MOD_PULSE2_ALG0_FREQ_STEP_VALUE                SIGMASTUDIOTYPE_8_24_CONVERT(1.04166666666667E-05)
#define MOD_PULSE2_ALG0_FREQ_STEP_TYPE                 SIGMASTUDIOTYPE_8_24
#define MOD_PULSE2_ALG0_ON_ADDR                        30
#define MOD_PULSE2_ALG0_ON_VALUE                       SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_PULSE2_ALG0_ON_TYPE                        SIGMASTUDIOTYPE_8_24
#define MOD_PULSE2_ALG0_TH_ADDR                        31
#define MOD_PULSE2_ALG0_TH_VALUE                       SIGMASTUDIOTYPE_8_24_CONVERT(0.5)
#define MOD_PULSE2_ALG0_TH_TYPE                        SIGMASTUDIOTYPE_8_24

/* Module READ_GPI6 - DSP Readback*/
#define MOD_READ_GPI6_COUNT                            1
#define MOD_READ_GPI6_DEVICE                           "IC1"
#define MOD_READ_GPI6_READBACKALGNEWSIGMA3001VALUE_ADDR 32
#define MOD_READ_GPI6_READBACKALGNEWSIGMA3001VALUE_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_READ_GPI6_READBACKALGNEWSIGMA3001VALUE_TYPE SIGMASTUDIOTYPE_8_24

/* Module Filter1 - General Eq (2nd order)*/
#define MOD_FILTER1_COUNT                              30
#define MOD_FILTER1_DEVICE                             "IC1"
#define MOD_FILTER1_ALG0_STAGE0_B2_ADDR                35
#define MOD_FILTER1_ALG0_STAGE0_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE0_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE0_B1_ADDR                36
#define MOD_FILTER1_ALG0_STAGE0_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE0_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE0_B0_ADDR                37
#define MOD_FILTER1_ALG0_STAGE0_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER1_ALG0_STAGE0_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE0_A2_ADDR                38
#define MOD_FILTER1_ALG0_STAGE0_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE0_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE0_A1_ADDR                39
#define MOD_FILTER1_ALG0_STAGE0_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE0_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE1_B2_ADDR                40
#define MOD_FILTER1_ALG0_STAGE1_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE1_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE1_B1_ADDR                41
#define MOD_FILTER1_ALG0_STAGE1_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE1_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE1_B0_ADDR                42
#define MOD_FILTER1_ALG0_STAGE1_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER1_ALG0_STAGE1_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE1_A2_ADDR                43
#define MOD_FILTER1_ALG0_STAGE1_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE1_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE1_A1_ADDR                44
#define MOD_FILTER1_ALG0_STAGE1_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE1_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE2_B2_ADDR                45
#define MOD_FILTER1_ALG0_STAGE2_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE2_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE2_B1_ADDR                46
#define MOD_FILTER1_ALG0_STAGE2_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE2_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE2_B0_ADDR                47
#define MOD_FILTER1_ALG0_STAGE2_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER1_ALG0_STAGE2_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE2_A2_ADDR                48
#define MOD_FILTER1_ALG0_STAGE2_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE2_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE2_A1_ADDR                49
#define MOD_FILTER1_ALG0_STAGE2_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE2_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE3_B2_ADDR                50
#define MOD_FILTER1_ALG0_STAGE3_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE3_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE3_B1_ADDR                51
#define MOD_FILTER1_ALG0_STAGE3_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE3_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE3_B0_ADDR                52
#define MOD_FILTER1_ALG0_STAGE3_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER1_ALG0_STAGE3_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE3_A2_ADDR                53
#define MOD_FILTER1_ALG0_STAGE3_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE3_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE3_A1_ADDR                54
#define MOD_FILTER1_ALG0_STAGE3_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE3_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE4_B2_ADDR                55
#define MOD_FILTER1_ALG0_STAGE4_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE4_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE4_B1_ADDR                56
#define MOD_FILTER1_ALG0_STAGE4_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE4_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE4_B0_ADDR                57
#define MOD_FILTER1_ALG0_STAGE4_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER1_ALG0_STAGE4_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE4_A2_ADDR                58
#define MOD_FILTER1_ALG0_STAGE4_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE4_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE4_A1_ADDR                59
#define MOD_FILTER1_ALG0_STAGE4_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE4_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE5_B2_ADDR                60
#define MOD_FILTER1_ALG0_STAGE5_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE5_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE5_B1_ADDR                61
#define MOD_FILTER1_ALG0_STAGE5_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE5_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE5_B0_ADDR                62
#define MOD_FILTER1_ALG0_STAGE5_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER1_ALG0_STAGE5_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE5_A2_ADDR                63
#define MOD_FILTER1_ALG0_STAGE5_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE5_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER1_ALG0_STAGE5_A1_ADDR                64
#define MOD_FILTER1_ALG0_STAGE5_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER1_ALG0_STAGE5_A1_TYPE                SIGMASTUDIOTYPE_8_24

/* Module Filter2 - General Eq (2nd order)*/
#define MOD_FILTER2_COUNT                              30
#define MOD_FILTER2_DEVICE                             "IC1"
#define MOD_FILTER2_ALG0_STAGE0_B2_ADDR                65
#define MOD_FILTER2_ALG0_STAGE0_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE0_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE0_B1_ADDR                66
#define MOD_FILTER2_ALG0_STAGE0_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE0_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE0_B0_ADDR                67
#define MOD_FILTER2_ALG0_STAGE0_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER2_ALG0_STAGE0_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE0_A2_ADDR                68
#define MOD_FILTER2_ALG0_STAGE0_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE0_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE0_A1_ADDR                69
#define MOD_FILTER2_ALG0_STAGE0_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE0_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE1_B2_ADDR                70
#define MOD_FILTER2_ALG0_STAGE1_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE1_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE1_B1_ADDR                71
#define MOD_FILTER2_ALG0_STAGE1_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE1_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE1_B0_ADDR                72
#define MOD_FILTER2_ALG0_STAGE1_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER2_ALG0_STAGE1_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE1_A2_ADDR                73
#define MOD_FILTER2_ALG0_STAGE1_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE1_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE1_A1_ADDR                74
#define MOD_FILTER2_ALG0_STAGE1_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE1_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE2_B2_ADDR                75
#define MOD_FILTER2_ALG0_STAGE2_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE2_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE2_B1_ADDR                76
#define MOD_FILTER2_ALG0_STAGE2_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE2_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE2_B0_ADDR                77
#define MOD_FILTER2_ALG0_STAGE2_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER2_ALG0_STAGE2_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE2_A2_ADDR                78
#define MOD_FILTER2_ALG0_STAGE2_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE2_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE2_A1_ADDR                79
#define MOD_FILTER2_ALG0_STAGE2_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE2_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE3_B2_ADDR                80
#define MOD_FILTER2_ALG0_STAGE3_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE3_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE3_B1_ADDR                81
#define MOD_FILTER2_ALG0_STAGE3_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE3_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE3_B0_ADDR                82
#define MOD_FILTER2_ALG0_STAGE3_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER2_ALG0_STAGE3_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE3_A2_ADDR                83
#define MOD_FILTER2_ALG0_STAGE3_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE3_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE3_A1_ADDR                84
#define MOD_FILTER2_ALG0_STAGE3_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE3_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE4_B2_ADDR                85
#define MOD_FILTER2_ALG0_STAGE4_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE4_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE4_B1_ADDR                86
#define MOD_FILTER2_ALG0_STAGE4_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE4_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE4_B0_ADDR                87
#define MOD_FILTER2_ALG0_STAGE4_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER2_ALG0_STAGE4_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE4_A2_ADDR                88
#define MOD_FILTER2_ALG0_STAGE4_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE4_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE4_A1_ADDR                89
#define MOD_FILTER2_ALG0_STAGE4_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE4_A1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE5_B2_ADDR                90
#define MOD_FILTER2_ALG0_STAGE5_B2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE5_B2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE5_B1_ADDR                91
#define MOD_FILTER2_ALG0_STAGE5_B1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE5_B1_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE5_B0_ADDR                92
#define MOD_FILTER2_ALG0_STAGE5_B0_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_FILTER2_ALG0_STAGE5_B0_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE5_A2_ADDR                93
#define MOD_FILTER2_ALG0_STAGE5_A2_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE5_A2_TYPE                SIGMASTUDIOTYPE_8_24
#define MOD_FILTER2_ALG0_STAGE5_A1_ADDR                94
#define MOD_FILTER2_ALG0_STAGE5_A1_VALUE               SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FILTER2_ALG0_STAGE5_A1_TYPE                SIGMASTUDIOTYPE_8_24

/* Module Gain1 - Gain*/
#define MOD_GAIN1_COUNT                                1
#define MOD_GAIN1_DEVICE                               "IC1"
#define MOD_GAIN1_GAINALGNS145X1GAIN_ADDR              95
#define MOD_GAIN1_GAINALGNS145X1GAIN_VALUE             SIGMASTUDIOTYPE_8_24_CONVERT(0.5)
#define MOD_GAIN1_GAINALGNS145X1GAIN_TYPE              SIGMASTUDIOTYPE_8_24

#endif
